In [7]:
import pandas as pd 
import numpy as np 
np.random.seed(45)
num_rows = 1000
mob_data = {
    "camera": np.random.randint(8, 201, size=num_rows),
    "Age": np.random.randint(8, 201, size=num_rows),
    "Ram": np.random.choice([4, 66, 8, 12, 16], size=num_rows),
    "Cpu_score": np.random.randint(40, 101, size=num_rows),
    "Slot_sd": np.random.randint(0, 2, size=num_rows),
    "Sims": np.random.choice([1, 2], size=num_rows),
    "Price": np.random.randint(900, 8010, size=num_rows)
}
df = pd.DataFrame(mob_data)
print(df)
df.to_csv("smartphone.csv", index=False)

     camera  Age  Ram  Cpu_score  Slot_sd  Sims  Price
0       166   52   16         83        0     1   3392
1       139  158    4         76        1     1   4887
2       132  106   16         69        1     2   1244
3        40   69    8         74        1     1   1558
4       103   63   66         77        1     1   4414
..      ...  ...  ...        ...      ...   ...    ...
995      19   59   66         92        0     2   3683
996     159   27    4         47        1     1   1354
997     155  105    4         53        0     2   2295
998      11  161   16         44        0     1   1562
999     133   97   12         49        1     2   2697

[1000 rows x 7 columns]

In [3]:
df.head()

   camera  Age  Row  Cpu_score  Slot_sd  Sims  Price
0     166   52   16         83        0     1   3392
1     139  158    4         76        1     1   4887
2     132  106   16         69        1     2   1244
3      40   69    8         74        1     1   1558
4     103   63   66         77        1     1   4414

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   camera     1000 non-null   int64
 1   Age        1000 non-null   int64
 2   Row        1000 non-null   int64
 3   Cpu_score  1000 non-null   int64
 4   Slot_sd    1000 non-null   int64
 5   Sims       1000 non-null   int64
 6   Price      1000 non-null   int64
dtypes: int64(7)
memory usage: 54.8 KB

In [5]:
df.describe()

,camera,Age,Row,Cpu_score,Slot_sd,Sims,Price
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,104.82700,106.562000,21.664000,70.607000,0.519000,1.506000,4479.356000
std,55.62846,54.903612,23.072135,17.915957,0.499889,0.500214,2050.314414
min,8.00000,8.000000,4.000000,40.000000,0.000000,1.000000,904.000000
25%,57.00000,61.000000,8.000000,56.000000,0.000000,1.000000,2776.500000
50%,103.50000,107.000000,12.000000,72.000000,1.000000,2.000000,4411.000000
75%,153.25000,154.000000,16.000000,86.000000,1.000000,2.000000,6230.250000
max,200.00000,200.000000,66.000000,100.000000,1.000000,2.000000,7999.000000