In [27]:
import pandas as pd

df = pd.read_csv('housing.csv')

# Clean column names (strip spaces, make lowercase to match easily)
df.columns = df.columns.str.strip()

# Define your desired columns (checking common variations)
desired_columns = [
    "Households", "Population", "House_median_age", "Total_rooms", 
    "Total_bedrooms", "Longitude", "Latitude", "Median_income", 
    "Median_house_value", "Ocean_proximity"
]


# This maps columns case-insensitively so it won't crash
column_mapping = {col.upper(): col for col in df.columns}
matched_cols = []
for col in desired_columns:
    # Look for exact or lowercase match
    if col in df.columns:
        matched_cols.append(col)
    elif col.upper() in column_mapping:
        matched_cols.append(column_mapping[col.upper()])

housing_data = df[matched_cols].copy()
housing_data

,households,population,total_rooms,total_bedrooms,longitude,latitude,median_income,median_house_value,ocean_proximity
0,126.0,322.0,880.0,129.0,-122.23,37.88,8.3252,452600.0,NEAR BAY
1,1138.0,2401.0,7099.0,1106.0,-122.22,37.86,8.3014,358500.0,NEAR BAY
2,177.0,496.0,1467.0,190.0,-122.24,37.85,7.2574,352100.0,NEAR BAY
3,219.0,558.0,1274.0,235.0,-122.25,37.85,5.6431,341300.0,NEAR BAY
4,259.0,565.0,1627.0,280.0,-122.25,37.85,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,330.0,845.0,1665.0,374.0,-121.09,39.48,1.5603,78100.0,INLAND
20636,114.0,356.0,697.0,150.0,-121.21,39.49,2.5568,77100.0,INLAND
20637,433.0,1007.0,2254.0,485.0,-121.22,39.43,1.7000,92300.0,INLAND
20638,349.0,741.0,1860.0,409.0,-121.32,39.43,1.8672,84700.0,INLAND
20639,530.0,1387.0,2785.0,616.0,-121.24,39.37,2.3886,89400.0,INLAND

['Households',
 'Population',
 'House_median_age',
 'Total_rooms',
 'Total_bedrooms',
 'Longitude',
 'Latitude',
 'Median_income',
 'Median_house_value',
 'Ocean_proximity']

In [38]:
 housing_data.columns = [
    "Households", "Population",  "Total_rooms", 
    "Total_bedrooms", "Longitude", "Latitude", "Median_income", 
    "Median_house_value", "Ocean_proximity"
].copy()
housing_data

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income,Median_house_value,Ocean_proximity
0,126.0,322.0,880.0,129.0,-122.23,37.88,8.3252,452600.0,NEAR BAY
1,1138.0,2401.0,7099.0,1106.0,-122.22,37.86,8.3014,358500.0,NEAR BAY
2,177.0,496.0,1467.0,190.0,-122.24,37.85,7.2574,352100.0,NEAR BAY
3,219.0,558.0,1274.0,235.0,-122.25,37.85,5.6431,341300.0,NEAR BAY
4,259.0,565.0,1627.0,280.0,-122.25,37.85,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,330.0,845.0,1665.0,374.0,-121.09,39.48,1.5603,78100.0,INLAND
20636,114.0,356.0,697.0,150.0,-121.21,39.49,2.5568,77100.0,INLAND
20637,433.0,1007.0,2254.0,485.0,-121.22,39.43,1.7000,92300.0,INLAND
20638,349.0,741.0,1860.0,409.0,-121.32,39.43,1.8672,84700.0,INLAND
20639,530.0,1387.0,2785.0,616.0,-121.24,39.37,2.3886,89400.0,INLAND

In [39]:
housing_data

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income,Median_house_value,Ocean_proximity
0,126.0,322.0,880.0,129.0,-122.23,37.88,8.3252,452600.0,NEAR BAY
1,1138.0,2401.0,7099.0,1106.0,-122.22,37.86,8.3014,358500.0,NEAR BAY
2,177.0,496.0,1467.0,190.0,-122.24,37.85,7.2574,352100.0,NEAR BAY
3,219.0,558.0,1274.0,235.0,-122.25,37.85,5.6431,341300.0,NEAR BAY
4,259.0,565.0,1627.0,280.0,-122.25,37.85,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,330.0,845.0,1665.0,374.0,-121.09,39.48,1.5603,78100.0,INLAND
20636,114.0,356.0,697.0,150.0,-121.21,39.49,2.5568,77100.0,INLAND
20637,433.0,1007.0,2254.0,485.0,-121.22,39.43,1.7000,92300.0,INLAND
20638,349.0,741.0,1860.0,409.0,-121.32,39.43,1.8672,84700.0,INLAND
20639,530.0,1387.0,2785.0,616.0,-121.24,39.37,2.3886,89400.0,INLAND

In [46]:
df2 = housing_data.sort_values(["Households","Median_income"],ascending=True).copy()
df2

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income,Median_house_value,Ocean_proximity
16171,1.0,13.0,8.0,1.0,-122.50,37.79,15.0001,500001.0,NEAR BAY
12286,2.0,8.0,6.0,2.0,-116.95,33.86,1.6250,55000.0,INLAND
3126,2.0,6.0,2.0,2.0,-117.79,35.21,2.3750,137500.0,INLAND
2511,2.0,28.0,49.0,7.0,-119.54,36.51,4.6250,162500.0,INLAND
12458,3.0,5.0,18.0,3.0,-114.62,33.62,0.5360,275000.0,INLAND
...,...,...,...,...,...,...,...,...,...
8985,4930.0,7431.0,18132.0,5419.0,-118.44,33.98,5.3359,500001.0,<1H OCEAN
6057,5050.0,15507.0,32054.0,5290.0,-117.78,34.03,6.0191,253900.0,<1H OCEAN
10309,5189.0,16122.0,37937.0,5471.0,-117.74,33.89,7.4947,366300.0,<1H OCEAN
13139,5358.0,16305.0,39320.0,6210.0,-121.44,38.43,4.9516,153700.0,INLAND
9880,6082.0,28566.0,32627.0,6445.0,-121.79,36.64,2.3087,118800.0,<1H OCEAN

In [50]:
df2.reset_index(drop=True,inplace= True)
df2

,Households,Population,Total_rooms,Total_bedrooms,Longitude,Latitude,Median_income,Median_house_value,Ocean_proximity
0,1.0,13.0,8.0,1.0,-122.50,37.79,15.0001,500001.0,NEAR BAY
1,2.0,8.0,6.0,2.0,-116.95,33.86,1.6250,55000.0,INLAND
2,2.0,6.0,2.0,2.0,-117.79,35.21,2.3750,137500.0,INLAND
3,2.0,28.0,49.0,7.0,-119.54,36.51,4.6250,162500.0,INLAND
4,3.0,5.0,18.0,3.0,-114.62,33.62,0.5360,275000.0,INLAND
...,...,...,...,...,...,...,...,...,...
20635,4930.0,7431.0,18132.0,5419.0,-118.44,33.98,5.3359,500001.0,<1H OCEAN
20636,5050.0,15507.0,32054.0,5290.0,-117.78,34.03,6.0191,253900.0,<1H OCEAN
20637,5189.0,16122.0,37937.0,5471.0,-117.74,33.89,7.4947,366300.0,<1H OCEAN
20638,5358.0,16305.0,39320.0,6210.0,-121.44,38.43,4.9516,153700.0,INLAND
20639,6082.0,28566.0,32627.0,6445.0,-121.79,36.64,2.3087,118800.0,<1H OCEAN

In [51]:
Final_data = df2.to_csv("Cleaned_Housing_Data.csv")
Final_data