In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Load the main dataset tab into a DataFrame
data = pd.read_excel('iris_dataset.xlsx', sheet_name='Iris Dataset')



# Display the first few rows to verify the headings
print(data.head())

X = data.iloc[:, :-1]  # All columns except the last as features
Y = data.iloc[:, -1]   # Last column as label
data
# print(df.info())
# y = df['SPECIES']

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [2]:
model = RandomForestClassifier()

In [3]:
model.fit(X,Y)

RandomForestClassifier()

In [4]:
X.values

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [5]:
predictions = model.predict([[5.1,3.5,1.4,0.2]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [6]:
predictions

array(['Iris-setosa'], dtype=object)

In [7]:
df1 = pd.read_excel("iris_test_aligned.xlsx")
df1

    sepal_length  sepal_width  petal_length  petal_width          species
0            5.4          3.0           4.5          1.5  Iris-versicolor
1            5.3          3.7           1.5          0.2      Iris-setosa
2            5.2          4.1           1.5          0.1      Iris-setosa
3            5.2          3.5           1.5          0.2      Iris-setosa
4            5.2          3.4           1.4          0.2      Iris-setosa
5            5.2          2.7           3.9          1.4  Iris-versicolor
6            5.1          3.8           1.9          0.4      Iris-setosa
7            5.1          3.8           1.6          0.2      Iris-setosa
8            5.1          3.8           1.5          0.3      Iris-setosa
9            5.1          3.7           1.5          0.4      Iris-setosa
10           5.1          3.5           1.4          0.2      Iris-setosa
11           5.1          3.5           1.4          0.3      Iris-setosa
12           5.1          3.4           1.5          0.2      Iris-setosa
13           5.1          3.3           1.7          0.5      Iris-setosa
14           5.1          2.5           3.0          1.1  Iris-versicolor
15           5.0          3.6           1.4          0.2      Iris-setosa
16           5.0          3.5           1.6          0.6      Iris-setosa
17           5.0          3.5           1.3          0.3      Iris-setosa
18           5.0          3.4           1.6          0.4      Iris-setosa
19           5.0          3.4           1.5          0.2      Iris-setosa
20           5.0          3.3           1.4          0.2      Iris-setosa
21           5.0          3.2           1.2          0.2      Iris-setosa
22           5.0          3.0           1.6          0.2      Iris-setosa
23           5.0          2.3           3.3          1.0  Iris-versicolor
24           5.0          2.0           3.5          1.0  Iris-versicolor
25           4.9          3.1           1.5          0.1      Iris-setosa
26           4.9          3.1           1.5          0.1      Iris-setosa
27           4.9          3.1           1.5          0.1      Iris-setosa
28           4.9          3.0           1.4          0.2      Iris-setosa
29           4.9          2.5           4.5          1.7   Iris-virginica
30           4.9          2.4           3.3          1.0  Iris-versicolor
31           4.8          3.4           1.9          0.2      Iris-setosa
32           4.8          3.4           1.6          0.2      Iris-setosa
33           4.8          3.1           1.6          0.2      Iris-setosa

In [8]:
testing = df1.iloc[: ,:-1]

In [9]:
testing

    sepal_length  sepal_width  petal_length  petal_width
0            5.4          3.0           4.5          1.5
1            5.3          3.7           1.5          0.2
2            5.2          4.1           1.5          0.1
3            5.2          3.5           1.5          0.2
4            5.2          3.4           1.4          0.2
5            5.2          2.7           3.9          1.4
6            5.1          3.8           1.9          0.4
7            5.1          3.8           1.6          0.2
8            5.1          3.8           1.5          0.3
9            5.1          3.7           1.5          0.4
10           5.1          3.5           1.4          0.2
11           5.1          3.5           1.4          0.3
12           5.1          3.4           1.5          0.2
13           5.1          3.3           1.7          0.5
14           5.1          2.5           3.0          1.1
15           5.0          3.6           1.4          0.2
16           5.0          3.5           1.6          0.6
17           5.0          3.5           1.3          0.3
18           5.0          3.4           1.6          0.4
19           5.0          3.4           1.5          0.2
20           5.0          3.3           1.4          0.2
21           5.0          3.2           1.2          0.2
22           5.0          3.0           1.6          0.2
23           5.0          2.3           3.3          1.0
24           5.0          2.0           3.5          1.0
25           4.9          3.1           1.5          0.1
26           4.9          3.1           1.5          0.1
27           4.9          3.1           1.5          0.1
28           4.9          3.0           1.4          0.2
29           4.9          2.5           4.5          1.7
30           4.9          2.4           3.3          1.0
31           4.8          3.4           1.9          0.2
32           4.8          3.4           1.6          0.2
33           4.8          3.1           1.6          0.2

In [10]:
predictions = model.predict(testing)

In [12]:
predictions

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)